modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/SolidBlock-cn/BRRP/issues"
license = "MPLv2"

[[mods]]
modId = "brrp_v1"
namespace = "brrp_v1"
version = "${version}"
displayName = "Better Runtime Resource Pack (BRRP) v1"
authors = "SolidBlock"
description = '''
BRRP is a library mod that can generate resource packs at runtime, instead of storing them as files. The mod is based on Advanced Runtime Resource Pack mod.
'''
#logoFile = ""

[[dependencies.brrp_v1]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brrp_v1]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.3)"
ordering = "NONE"
side = "BOTH"
